/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package reservasalon;

import java.awt.Font;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author Tony
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        setThemesMenu();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        letraPeque2 = new javax.swing.JLabel();
        letraMedia3 = new javax.swing.JLabel();
        letraPeque1 = new javax.swing.JLabel();
        tamanhos = new javax.swing.JComboBox<>();
        temas = new javax.swing.JComboBox<>();
        letraGrande = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        letraMedia2 = new javax.swing.JLabel();
        letraMedia1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(244, 255, 230));

        jPanel2.setBackground(new java.awt.Color(211, 239, 175));

        letraPeque2.setBackground(new java.awt.Color(61, 61, 61));
        letraPeque2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        letraPeque2.setForeground(new java.awt.Color(61, 61, 61));
        letraPeque2.setText("Tamaño de letra:");

        letraMedia3.setBackground(new java.awt.Color(61, 61, 61));
        letraMedia3.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        letraMedia3.setForeground(new java.awt.Color(61, 61, 61));
        letraMedia3.setText("Aspecto");

        letraPeque1.setBackground(new java.awt.Color(61, 61, 61));
        letraPeque1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        letraPeque1.setForeground(new java.awt.Color(61, 61, 61));
        letraPeque1.setText("Tema:");

        tamanhos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Normal", "Pequeña", "Grande" }));
        tamanhos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tamanhosActionPerformed(evt);
            }
        });

        temas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "juan1", "juan2", "Item 3", "Item 4" }));
        temas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                temasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(letraPeque1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(temas, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(letraPeque2)
                        .addGap(28, 28, 28)
                        .addComponent(tamanhos, 0, 112, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(112, Short.MAX_VALUE)
                    .addComponent(letraMedia3)
                    .addGap(94, 94, 94)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(temas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(letraPeque1))
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tamanhos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(letraPeque2))
                .addGap(59, 59, 59))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(letraMedia3)
                    .addContainerGap(164, Short.MAX_VALUE)))
        );

        letraGrande.setBackground(new java.awt.Color(61, 61, 61));
        letraGrande.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        letraGrande.setForeground(new java.awt.Color(61, 61, 61));
        letraGrande.setText("Dino Hotel");
        letraGrande.setAlignmentY(0.0F);

        jPanel3.setBackground(new java.awt.Color(211, 239, 175));

        jButton1.setBackground(new java.awt.Color(163, 232, 73));
        jButton1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(61, 61, 61));
        jButton1.setText("Reserva aquí");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        letraMedia2.setBackground(new java.awt.Color(61, 61, 61));
        letraMedia2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        letraMedia2.setForeground(new java.awt.Color(61, 61, 61));
        letraMedia2.setText("Reservas");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(letraMedia2)
                .addGap(94, 94, 94))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(jButton1)
                .addContainerGap(86, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(letraMedia2)
                .addGap(49, 49, 49)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(68, Short.MAX_VALUE))
        );

        letraMedia1.setBackground(new java.awt.Color(61, 61, 61));
        letraMedia1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        letraMedia1.setForeground(new java.awt.Color(61, 61, 61));
        letraMedia1.setText("Congresos, banquetes, jornadas");
        letraMedia1.setAlignmentY(0.0F);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/reservasalon/pie.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(408, 408, 408)
                .addComponent(letraGrande)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(150, 150, 150))
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(316, Short.MAX_VALUE)
                    .addComponent(letraMedia1)
                    .addGap(311, 311, 311)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(letraGrande)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 130, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(86, 86, 86)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(124, 124, 124)
                    .addComponent(letraMedia1)
                    .addContainerGap(444, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        setVisible(false);
        new Interface(temas.getSelectedIndex(),tamanhos.getSelectedIndex()).setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void temasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_temasActionPerformed
        int pressed=temas.getSelectedIndex();
        System.out.println(pressed);
        try {
            if(pressed==0){
                for (UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                    if ("Nimbus".equals(info.getName())) {
                        UIManager.setLookAndFeel(info.getClassName());
                        break;
                    }
                }
            }else{
                UIManager.setLookAndFeel(UIManager.getInstalledLookAndFeels()[pressed-1].getClassName());
            }
        } catch (Exception ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_temasActionPerformed

    private void tamanhosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tamanhosActionPerformed
        int pressed=tamanhos.getSelectedIndex();
        
        switch(pressed){
            case 0:
                letraGrande.setFont(new Font(letraGrande.getFont().getName(), Font.BOLD,36));
                letraMedia1.setFont(new Font(letraMedia1.getFont().getName(), Font.BOLD,24));
                letraMedia2.setFont(new Font(letraMedia2.getFont().getName(), Font.BOLD,24));
                letraMedia3.setFont(new Font(letraMedia3.getFont().getName(), Font.BOLD,24));
                letraPeque1.setFont(new Font(letraPeque1.getFont().getName(), Font.BOLD,18));
                letraPeque2.setFont(new Font(letraPeque2.getFont().getName(), Font.BOLD,18));        
                break;
            case 1:
                letraGrande.setFont(new Font(letraGrande.getFont().getName(), Font.BOLD,24));
                letraMedia1.setFont(new Font(letraMedia1.getFont().getName(), Font.BOLD,18));
                letraMedia2.setFont(new Font(letraMedia2.getFont().getName(), Font.BOLD,18));
                letraMedia3.setFont(new Font(letraMedia3.getFont().getName(), Font.BOLD,18));
                letraPeque1.setFont(new Font(letraPeque1.getFont().getName(), Font.BOLD,12));
                letraPeque2.setFont(new Font(letraPeque2.getFont().getName(), Font.BOLD,12));
                break;
            default:
                letraGrande.setFont(new Font(letraGrande.getFont().getName(), Font.BOLD,40));
                letraMedia1.setFont(new Font(letraMedia1.getFont().getName(), Font.BOLD,36));
                letraMedia2.setFont(new Font(letraMedia2.getFont().getName(), Font.BOLD,36));
                letraMedia3.setFont(new Font(letraMedia3.getFont().getName(), Font.BOLD,36));
                letraPeque1.setFont(new Font(letraPeque1.getFont().getName(), Font.BOLD,24));
                letraPeque2.setFont(new Font(letraPeque2.getFont().getName(), Font.BOLD,24));
                break;
        }
    }//GEN-LAST:event_tamanhosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel letraGrande;
    private javax.swing.JLabel letraMedia1;
    private javax.swing.JLabel letraMedia2;
    private javax.swing.JLabel letraMedia3;
    private javax.swing.JLabel letraPeque1;
    private javax.swing.JLabel letraPeque2;
    private javax.swing.JComboBox<String> tamanhos;
    private javax.swing.JComboBox<String> temas;
    // End of variables declaration//GEN-END:variables

    private void setThemesMenu() {
        String[]themes=new String[UIManager.getInstalledLookAndFeels().length+1];
        themes[0]="Por defecto";
        for(int i=1;i<themes.length;i++){
            themes[i]=UIManager.getInstalledLookAndFeels()[i-1].getName();
        }
        temas.setModel(new javax.swing.DefaultComboBoxModel<>(themes));
    }
}
